### ISSUE TITLE
D

### ISSUE THREAD

**Issue by Dirtroadp** [UndedInside/DuckyScripts#2]
https://github.com/inaz0/flipperZero/blob/refs%2Fheads%2Fmain/badusb%2Fandroid%2Fpin_brute_force%2Ftop65_4digit_pin_bf.txt#L14-L580

**Comment by UndedInside** [comment]
I wish there was a way of scripting ducky programs a bit better because I personally find these brute force programs to be clumsy (nothing against the authors of them - I've certainly written them in the past).

If you've written a payload feel free to create a merge request. I'd rather not include other people's payloads without their consent but one of your own making is absolutely welcome
